### ISSUE TITLE
Error when creating more than 1 local collection

### ISSUE THREAD

**Issue by mngibso** [vazco/universe-core#1]
Mongo.Collection allows you to create "an unmanaged (unsynchronized) local collection" by sending null in place of name:
var LocalCollection = Mongo.Collection(null);

I can do this with ONE UniCollection, but if I try to create a second local UniCollection I get the following error:

Uncaught Error: Type nullDoc already present   ejson.js:110

**Comment by mngibso** [comment]
Sorry - this should be in meteor-universe-collection

**Comment by radekmie** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
